### ISSUE TITLE
Todo ideas

### ISSUE THREAD

**Issue by raul-sauco** [raul-sauco/coding-challenges#5]
Some fun-looking problems:

- [x] [10. Regular Expression Matching](https://leetcode.com/problems/regular-expression-matching/)
- [x] [174. Dungeon Game](https://leetcode.com/problems/dungeon-game/)
- [x] [312. Burst Balloons](https://leetcode.com/problems/burst-balloons/)
- [ ] [407. Trapping Rain Water II](https://leetcode.com/problems/trapping-rain-water-ii/description/)
- [ ] [1036. Escape a Large Maze](https://leetcode.com/problems/escape-a-large-maze/)
- [ ] [1143. Longest Common Subsequence Rust](https://leetcode.com/problems/longest-common-subsequence/)
